import logging
from flask import Flask, jsonify

# Logging sozlamalari (Professional DevOps uslubi)
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("AgricultureApp")

app = Flask(__name__)

@app.route('/')
def home():
    logger.info("Accessing the Farming Procurement Dashboard")
    return "Farming Procurement System - Shohjahon Edition"

@app.route('/api/status')
def get_status():
    # O'zgaruvchi nomlari o'zgartirildi
    crop_inventory = {
        "status": "Operational",
        "farmer_id": "SH-59",
        "node_health": "100%"
    }
    return jsonify(crop_inventory)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
